export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SELECT_MAIN_SECTION = 'SELECT_MAIN_SECTION';
export const CHANGE_STATE_MEMBER = 'CHANGE_STATE_MEMBER';
